services:
  myproject:
    build:
      context: ./spring-event-practice/
      dockerfile: Dockerfile
    image: spring-event-practice:1.0
    networks:
      starbug_network:
        ipv4_address: 172.30.0.151
    container_name: spring-event-practice
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/volumes/project/practice-demo/spring-event-practice/logs:/usr/app/logs
    ports:
      - "18080:18080"
networks:
  starbug_network:
    name: starbug_network
    external: true