version: "3.8"
services:
  myproject:
    build:
      context: ./spring-event-practice/
      dockerfile: Dockerfile
    image: spring-event-practice:1.0
    networks:
      starbug_network:
        ipv4_address: 172.30.0.151
    container_name: spring-event-practice
    ports:
      - "18080:18080"
networks:
  starbug_network:
    name: starbug_network
    external: true